//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace youtube
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Description { get; set; }
        public string Price { get; set; }
        public string PricePerUnit { get; set; }
        public string Offers { get; set; }
        public string Supermarket { get; set; }
        public string Department { get; set; }
        public string Section { get; set; }
        public string Shelf { get; set; }
        public string Brand { get; set; }
        public System.DateTime dtmAdded { get; set; }
        public string ProdID { get; set; }
        public Nullable<decimal> iPrice { get; set; }
        public int text_id { get; set; }
        public string Search { get; set; }
        public string CONCAT { get; set; }
    }
}
